spring:
  application:
    name: pharma.PA
  profiles:
    active: local
---
spring:
  profile: local
  datasource:
    url: jdbc:postgresql://181.143.211.54:3654/desarrollo
    username: postgres
    password: sume3654
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update